### PR TITLE
Update github.com/temporalio/ui-server

### PR DESCRIPTION
**Pull request by jlegrone**
**What changed?**

Updates ui-server to the latest ~tagged release~ commit. ~Dependabot should be able to start tracking new versions going forward.~

Update: We're still unable to use a tagged release until a new version is cut now that https://github.com/temporalio/ui/pull/267 is merged.

**Why?**

**How did you test it?**

**Potential risks**

**Is hotfix candidate?**

### CODE REVIEW

**Comment by jlegrone** [comment]
Setting this PR to draft for now; loading the UI at this version results in the error `invalid query: unable to convert filter expression: unable to convert values of comparison expression: StartTime only supports BETWEEN ... AND ... filter`

```
go.temporal.io/server/common/log.(*zapLogger).Error
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/log/zap_logger.go:142
go.temporal.io/server/common/persistence/visibility.(*visibilityManagerMetrics).updateErrorMetric
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/persistence/visibility/visiblity_manager_metrics.go:196
go.temporal.io/server/common/persistence/visibility.(*visibilityManagerMetrics).ListWorkflowExecutions
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/persistence/visibility/visiblity_manager_metrics.go:149
go.temporal.io/server/service/frontend.(*WorkflowHandler).ListWorkflowExecutions
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/service/frontend/workflowHandler.go:2267
go.temporal.io/server/service/frontend.(*DCRedirectionHandlerImpl).ListWorkflowExecutions.func2
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/service/frontend/dcRedirectionHandler.go:405
go.temporal.io/server/service/frontend.(*NoopRedirectionPolicy).WithNamespaceRedirect
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/service/frontend/dcRedirectionPolicy.go:118
go.temporal.io/server/service/frontend.(*DCRedirectionHandlerImpl).ListWorkflowExecutions
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/service/frontend/dcRedirectionHandler.go:401
go.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler.func1
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1482
go.temporal.io/server/common/authorization.(*interceptor).Interceptor
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/authorization/interceptor.go:152
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1116
go.temporal.io/server/common/rpc/interceptor.(*NamespaceCountLimitInterceptor).Intercept
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/interceptor/namespace_count_limit.go:98
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/rpc/interceptor.(*NamespaceRateLimitInterceptor).Intercept
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/interceptor/namespace_rate_limit.go:88
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/rpc/interceptor.(*RateLimitInterceptor).Intercept
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/interceptor/rate_limit.go:83
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/rpc/interceptor.(*NamespaceValidatorInterceptor).Intercept
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/interceptor/namespace_validator.go:113
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/rpc/interceptor.(*TelemetryInterceptor).Intercept
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/interceptor/telemetry.go:108
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/metrics.NewServerMetricsContextInjectorInterceptor.func1
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/metrics/grpc.go:66
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/rpc.ServiceErrorInterceptor
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/grpc.go:131
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
go.temporal.io/server/common/rpc/interceptor.(*NamespaceLogInterceptor).Intercept
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/server@v1.14.4/common/rpc/interceptor/namespace_logger.go:84
google.golang.org/grpc.chainUnaryInterceptors.func1.1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1119
google.golang.org/grpc.chainUnaryInterceptors.func1
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1121
go.temporal.io/api/workflowservice/v1._WorkflowService_ListWorkflowExecutions_Handler
    /Users/jacob.legrone/go/pkg/mod/go.temporal.io/api@v1.7.0/workflowservice/v1/service.pb.go:1484
google.golang.org/grpc.(*Server).processUnaryRPC
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1282
google.golang.org/grpc.(*Server).handleStream
    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:1616
google.golang.org/grpc.(*Server).serveStreams.func1.2    /Users/jacob.legrone/go/pkg/mod/google.golang.org/grpc@v1.42.0/server.go:921
```

**Comment by nadilas** [comment]
I checked again after the latest bump of temporal server to `1.15.0`

The same config server `1.15.0` and ui-server `0.2.0` works in https://github.com/temporalio/docker-compose/blob/fa3a53ece0473514a9a8ee2915f750c48eaf6831/docker-compose-ui-experimental.yml#L42

The embedded ui-server 0.2.0 doesn't throw errors on the backend, but the ui uses an older `api` v1.5.0 and the same error bubbles up to the new ui.

**Comment by jlegrone** [comment]
Blocking on https://github.com/temporalio/ui/issues/249

**Comment by jlegrone** [comment]
Now blocking on https://github.com/temporalio/ui-server/pull/106

**Pull request merged**
