### PR TITLE
Upgrade Temporal and Temporal Web UI.

### PR DESCRIPTION
**Pull request by robholland**
**What changed?**

Temporal and Temporal Web UI versions upgraded.

**Why?**

To benefit from the improved web UI.

**How did you test it?**

Ran locally and in gitpod.

**Potential risks**

None.

**Is hotfix candidate?**

No.

### CODE REVIEW

**Comment by robholland** [comment]
It is not compatible, I will adjust the code.

**Comment by robholland** [comment]
The SQLite pragma issue is now fixed: https://github.com/temporalio/temporal/pull/3031 

I will update this PR once the fix is in a release.

**Comment by robholland** [comment]
This is failing builds due to: https://github.com/temporalio/ui-server/issues/80 which now seems to be considered as an error not a warning for the tests. Not sure what to do here :/

**Comment by jlegrone** [comment]
Hmm... the reproduction case in https://github.com/temporalio/ui-server/issues/80 doesn't panic. I'm not sure what's going on here exactly, do you mind rebasing now that #89 is merged?

**Review by jlegrone — APPROVED** [review]

**Comment by robholland** [comment]
Please revert this, the ui-server code isn't quite right and causes errors when using the UI.

**Pull request merged**
